export const data = [
  {
    Referència: 'JD12',
    Descripció: "Accessoris d'escacs",
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/392-507-accessoris-d-escacs.html#/188-mida-40mm_i_78mm',
    Imàtges:
      'https://can-cels.com/697-technology_large_default/accessoris-d-escacs.jpg',
    'preu major': '36,96€',
    'Marge 50%': '18,48€',
    'Base Impossable': '55,44€',
    '21%IVA': '11,64 €',
    'Preu Venta Públic': '67,08€',
  },
  {
    Referència: 'JD13',
    Descripció: 'Accessoris de dames',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/393-508-accessoris-de-dames.html#/189-mida-24_mm_o',
    Imàtges:
      'https://can-cels.com/698-technology_large_default/accessoris-de-dames.jpg',
    'preu major': '5,69€',
    'Marge 50%': '2,85€',
    'Base Impossable': '8,54€',
    '21%IVA': '1,79 €',
    'Preu Venta Públic': '10,33€',
  },
  {
    Referència: 'JD09',
    Descripció: 'Accessoris oca i parxís',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/399-512-accessoris-oca-i-parxis.html#/192-mida-53_mm_largo_x_34mm_o_pieza_15mm_o',
    Imàtges:
      'https://can-cels.com/704-technology_large_default/accessoris-oca-i-parxis.jpg',
    'preu major': '5,04€',
    'Marge 50%': '2,52€',
    'Base Impossable': '7,56€',
    '21%IVA': '1,59 €',
    'Preu Venta Públic': '9,15€',
  },
  {
    Referència: 'XE87',
    Descripció: 'Agulles de mitja 5mmx50cm',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/756-1043-agulles-de-mitja.html#/275-mida-o_5_mm_x50_cm',
    Imàtges:
      'https://can-cels.com/1063-technology_large_default/agulles-de-mitja.jpg',
    'preu major': '1,27€',
    'Marge 50%': '0,64€',
    'Base Impossable': '1,91€',
    '21%IVA': '0,40 €',
    'Preu Venta Públic': '2,31€',
  },
  {
    Referència: 'AN01',
    Descripció: 'Anella de faig 20mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/414-436-anella-de-faig.html#/116-mida-o_20_36_mm',
    Imàtges:
      'https://can-cels.com/721-technology_large_default/anella-de-faig.jpg',
    'preu major': '0,17€',
    'Marge 50%': '0,17€',
    'Base Impossable': '0,34€',
    '21%IVA': '0,07 €',
    'Preu Venta Públic': '0,41€',
  },
  {
    Referència: 'JD56',
    Descripció: 'Apilable arc de Sant Martí',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/483-542-apilable-arc-de-sant-marti-.html#/88-mida-15_cm',
    Imàtges:
      'https://can-cels.com/884-technology_large_default/apilable-arc-de-sant-marti-.jpg',
    'preu major': '3,06€',
    'Marge 50%': '1,53€',
    'Base Impossable': '4,59€',
    '21%IVA': '0,96 €',
    'Preu Venta Públic': '5,55€',
  },
  {
    Referència: 'JC82',
    Descripció: 'Arc amb 2 fletxes',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/550-586-arc-amb-2-fletxes.html#/247-mida-90_cm',
    Imàtges:
      'https://can-cels.com/859-technology_large_default/arc-amb-2-fletxes.jpg',
    'preu major': '3,23€',
    'Marge 50%': '1,62€',
    'Base Impossable': '4,85€',
    '21%IVA': '1,02 €',
    'Preu Venta Públic': '5,86€',
  },
  {
    Referència: 'DV53',
    Descripció: 'Arc Iris color',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/706-arc-iris-color.html',
    Imàtges:
      'https://can-cels.com/1034-technology_large_default/arc-iris-color.jpg',
    'preu major': '8,45€',
    'Marge 50%': '4,65€',
    'Base Impossable': '13,10€',
    '21%IVA': '2,75 €',
    'Preu Venta Públic': '16,00€',
  },
  {
    Referència: 'DV54',
    Descripció: 'Arc Iris natural',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/705-arc-iris-natural.html',
    Imàtges:
      'https://can-cels.com/1033-technology_large_default/arc-iris-natural.jpg',
    'preu major': '6,56€',
    'Marge 50%': '3,38€',
    'Base Impossable': '9,94€',
    '21%IVA': '2,09 €',
    'Preu Venta Públic': '12,00€',
  },
  {
    Referència: 'CU115',
    Descripció: 'Argolla per tovallons',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/639-700-argolla-per-tovallons.html#/40-mida-o_60_mm',
    Imàtges:
      'https://can-cels.com/920-technology_large_default/argolla-per-tovallons.jpg',
    'preu major': '1,22€',
    'Marge 50%': '0,61€',
    'Base Impossable': '1,83€',
    '21%IVA': '0,38 €',
    'Preu Venta Públic': '2,21€',
  },
  {
    Referència: 'JC45',
    Descripció: 'Arrosegall ànec',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/707-arrosegall-anec.html',
    Imàtges:
      'https://can-cels.com/1032-technology_large_default/arrosegall-anec.jpg',
    'preu major': '11,49€',
    'Marge 50%': '5,75€',
    'Base Impossable': '17,24€',
    '21%IVA': '3,62 €',
    'Preu Venta Públic': '20,85€',
  },
  {
    Referència: 'AR01',
    Descripció: 'Arrossegador ànec groc',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/480-arrossegador-anec-groc.html',
    Imàtges:
      'https://can-cels.com/763-technology_large_default/arrossegador-anec-groc.jpg',
    'preu major': '11,37€',
    'Marge 50%': '5,69€',
    'Base Impossable': '17,06€',
    '21%IVA': '3,58 €',
    'Preu Venta Públic': '20,64€',
  },
  {
    Referència: 'AR03',
    Descripció: 'Arrossegador ànec natural',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/479-arrossegador-anec-natural.html',
    Imàtges:
      'https://can-cels.com/957-technology_large_default/arrossegador-anec-natural.jpg',
    'preu major': '9,45€',
    'Marge 50%': '4,73€',
    'Base Impossable': '14,18€',
    '21%IVA': '2,98 €',
    'Preu Venta Públic': '17,15€',
  },
  {
    Referència: 'AR07',
    Descripció: 'Arrossegador gallina natural/groga',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/481-540-arrossegador-gallina-naturalgroga.html#/46-color-natural',
    Imàtges:
      'https://can-cels.com/764-technology_large_default/arrossegador-gallina-naturalgroga.jpg',
    'preu major': '11,29€',
    'Marge 50%': '5,65€',
    'Base Impossable': '16,94€',
    '21%IVA': '3,56 €',
    'Preu Venta Públic': '20,49€',
  },
  {
    Referència: 'AR04',
    Descripció: 'Arrossegador gat',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/478-arrossegador-gat.html',
    Imàtges:
      'https://can-cels.com/761-technology_large_default/arrossegador-gat.jpg',
    'preu major': '13,16€',
    'Marge 50%': '6,58€',
    'Base Impossable': '19,74€',
    '21%IVA': '4,15 €',
    'Preu Venta Públic': '23,89€',
  },
  {
    Referència: 'AR05',
    Descripció: 'Arrossegament assortiment animals',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/482-arrossegament-assortiment-animals.html',
    Imàtges:
      'https://can-cels.com/765-technology_large_default/arrossegament-assortiment-animals.jpg',
    'preu major': '2,74€',
    'Marge 50%': '1,37€',
    'Base Impossable': '4,11€',
    '21%IVA': '0,86 €',
    'Preu Venta Públic': '4,97€',
  },
  {
    Referència: 'BA10/BA11*',
    Descripció: 'BALDUFA A CORDILL 36mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/428-485-baldufa-a-cordill.html#/175-mida-36_mm_o',
    Imàtges:
      'https://can-cels.com/860-technology_large_default/baldufa-a-cordill.jpg',
    'preu major': '0,39€',
    'Marge 50%': '0,27€',
    'Base Impossable': '0,66€',
    '21%IVA': '0,14 €',
    'Preu Venta Públic': '0,80€',
  },
  {
    Referència: 'BP21',
    Descripció: 'Baldufa amb forma de ceba colors assortits 49mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/377-495-baldufa-amb-forma-de-ceba-colors-assortits.html#/181-mida-49mm_o',
    Imàtges:
      'https://can-cels.com/685-technology_large_default/baldufa-amb-forma-de-ceba-colors-assortits.jpg',
    'preu major': '0,59€',
    'Marge 50%': '0,59€',
    'Base Impossable': '1,18€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,43€',
  },
  {
    Referència: 'BP11',
    Descripció: 'Baldufa amb forma de pera colors assortits 49mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/375-494-baldufa-amb-forma-de-pera-colors-assortits.html#/181-mida-49mm_o',
    Imàtges:
      'https://can-cels.com/684-technology_large_default/baldufa-amb-forma-de-pera-colors-assortits.jpg',
    'preu major': '0,59€',
    'Marge 50%': '0,59€',
    'Base Impossable': '1,18€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,43€',
  },
  {
    Referència: 'BG31',
    Descripció: 'Baldufa BG31 10cm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/baldufes/693-954-baldufa-bg31.html#/41-mida-o_10_cm',
    Imàtges:
      'https://can-cels.com/1029-technology_large_default/baldufa-bg31.jpg',
    'preu major': '5,69€',
    'Marge 50%': '2,85€',
    'Base Impossable': '8,54€',
    '21%IVA': '1,79 €',
    'Preu Venta Públic': '10,33€',
  },
  {
    Referència: 'BM86',
    Descripció: "Baldufa d' Alzina 48mm",
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/373-489-baldufa-d-alzina.html#/173-mida-48mm_o',
    Imàtges:
      'https://can-cels.com/682-technology_large_default/baldufa-d-alzina.jpg',
    'preu major': '1,16€',
    'Marge 50%': '1,16€',
    'Base Impossable': '2,32€',
    '21%IVA': '0,49 €',
    'Preu Venta Públic': '2,81€',
  },
  {
    Referència: 'BB02',
    Descripció: 'Baldufa de boix 40mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/657-734-baldufa-de-boix.html#/153-mida-40_mm_o',
    Imàtges:
      'https://can-cels.com/896-technology_large_default/baldufa-de-boix.jpg',
    'preu major': '1,72€',
    'Marge 50%': '0,86€',
    'Base Impossable': '2,58€',
    '21%IVA': '0,54 €',
    'Preu Venta Públic': '3,12€',
  },
  {
    Referència: 'BC10',
    Descripció: 'Baldufa de faig 40mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/655-727-baldufa-de-faig.html#/153-mida-40_mm_o',
    Imàtges:
      'https://can-cels.com/895-technology_large_default/baldufa-de-faig.jpg',
    'preu major': '0,59€',
    'Marge 50%': '0,59€',
    'Base Impossable': '1,18€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,43€',
  },
  {
    Referència: 'BC12/13*',
    Descripció: 'Baldufa de faig de colors 40mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/424-477-baldufa-de-faig-de-colors.html#/153-mida-40_mm_o',
    Imàtges:
      'https://can-cels.com/719-technology_large_default/baldufa-de-faig-de-colors.jpg',
    'preu major': '0,59€',
    'Marge 50%': '0,59€',
    'Base Impossable': '1,18€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,43€',
  },
  {
    Referència: 'BC12/13*',
    Descripció: 'Baldufa de faig de colors 55mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/424-477-baldufa-de-faig-de-colors.html#/153-mida-40_mm_o',
    Imàtges:
      'https://can-cels.com/719-technology_large_default/baldufa-de-faig-de-colors.jpg',
    'preu major': '0,92€',
    'Marge 50%': '0,92€',
    'Base Impossable': '1,84€',
    '21%IVA': '0,39 €',
    'Preu Venta Públic': '2,23€',
  },
  {
    Referència: 'JC04',
    Descripció: 'Baldufa especial de faig 52mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/380-1000-baldufa-especial-de-faig.html#/174-mida-52mm_o',
    Imàtges:
      'https://can-cels.com/688-technology_large_default/baldufa-especial-de-faig.jpg',
    'preu major': '1,37€',
    'Marge 50%': '1,10€',
    'Base Impossable': '2,47€',
    '21%IVA': '0,52 €',
    'Preu Venta Públic': '3,00€',
  },
  {
    Referència: 'TM4002',
    Descripció: 'Baldufa gran de faig amb anella decorativa',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/427-484-baldufa-gran-de-faig-amb-anella-decorativa.html#/178-mida-62_mm_o',
    Imàtges:
      'https://can-cels.com/720-technology_large_default/baldufa-gran-de-faig-amb-anella-decorativa.jpg',
    'preu major': '2,77€',
    'Marge 50%': '1,39€',
    'Base Impossable': '4,16€',
    '21%IVA': '0,87 €',
    'Preu Venta Públic': '5,03€',
  },
  {
    Referència: 'TM4002',
    Descripció: 'Baldufa gran TM4002',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/baldufes/701-999-baldufa-gran-tm4002.html#/178-mida-62_mm_o',
    Imàtges:
      'https://can-cels.com/1083-technology_large_default/baldufa-gran-tm4002.jpg',
    'preu major': '1,61€',
    'Marge 50%': '0,81€',
    'Base Impossable': '2,42€',
    '21%IVA': '0,51 €',
    'Preu Venta Públic': '2,92€',
  },
  {
    Referència: 'BM10/BM11*',
    Descripció: 'Baldufa M. Creu / Gran 46mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/369-482-baldufa-m-creu-gran.html#/179-mida-46mm_o',
    Imàtges:
      'https://can-cels.com/679-technology_large_default/baldufa-m-creu-gran.jpg',
    'preu major': '0,52€',
    'Marge 50%': '0,52€',
    'Base Impossable': '1,04€',
    '21%IVA': '0,22 €',
    'Preu Venta Públic': '1,26€',
  },
  {
    Referència: 'BM10/BM11*',
    Descripció: 'Baldufa M. Creu / Gran 56mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/369-482-baldufa-m-creu-gran.html#/179-mida-46mm_o',
    Imàtges:
      'https://can-cels.com/679-technology_large_default/baldufa-m-creu-gran.jpg',
    'preu major': '0,94€',
    'Marge 50%': '0,94€',
    'Base Impossable': '1,88€',
    '21%IVA': '0,39 €',
    'Preu Venta Públic': '2,27€',
  },
  {
    Referència: 'BB50',
    Descripció: 'BALDUFA MINI BOIX 21mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/702-1002-baldufa-mini-boix.html#/184-mida-21mm_o',
    Imàtges:
      'https://can-cels.com/1031-technology_large_default/baldufa-mini-boix.jpg',
    'preu major': '0,44€',
    'Marge 50%': '0,44€',
    'Base Impossable': '0,88€',
    '21%IVA': '0,18 €',
    'Preu Venta Públic': '1,06€',
  },
  {
    Referència: 'BB51',
    Descripció: 'BALDUFA MINI ROMBES FAIG 27mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/390-506--baldufa-mini-rombes-faig.html#/187-mida-27mm_o',
    Imàtges:
      'https://can-cels.com/695-technology_large_default/-baldufa-mini-rombes-faig.jpg',
    'preu major': '0,89€',
    'Marge 50%': '0,89€',
    'Base Impossable': '1,78€',
    '21%IVA': '0,37 €',
    'Preu Venta Públic': '2,15€',
  },
  {
    Referència: 'BR00',
    Descripció: 'Baldufa ratllada 42mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/658-738-baldufa-ratllada.html#/186-mida-42mm_o',
    Imàtges:
      'https://can-cels.com/897-technology_large_default/baldufa-ratllada.jpg',
    'preu major': '0,64€',
    'Marge 50%': '0,64€',
    'Base Impossable': '1,28€',
    '21%IVA': '0,27 €',
    'Preu Venta Públic': '1,55€',
  },
  {
    Referència: 'BT00',
    Descripció: 'BALDUFA TURCA 46mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/378-998-baldufa-turca.html#/179-mida-46mm_o',
    Imàtges:
      'https://can-cels.com/686-technology_large_default/baldufa-turca.jpg',
    'preu major': '1,14€',
    'Marge 50%': '1,14€',
    'Base Impossable': '2,28€',
    '21%IVA': '0,48 €',
    'Preu Venta Públic': '2,76€',
  },
  {
    Referència: 'JC47',
    Descripció: 'BALLARÍ BOIX TIPUS BALDUFA',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/385-500-ballari-boix-tipus-baldufa.html#/128-mida-o_20_mm',
    Imàtges:
      'https://can-cels.com/990-technology_large_default/ballari-boix-tipus-baldufa.jpg',
    'preu major': '0,21€',
    'Marge 50%': '0,21€',
    'Base Impossable': '0,42€',
    '21%IVA': '0,09 €',
    'Preu Venta Públic': '0,51€',
  },
  {
    Referència: 'JC80',
    Descripció: 'BALLARÍ BOIX TIPUS BALDUFA COLOR',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/384-499-ballari-boix-tipus-baldufa-color.html#/128-mida-o_20_mm',
    Imàtges:
      'https://can-cels.com/691-technology_large_default/ballari-boix-tipus-baldufa-color.jpg',
    'preu major': '0,24€',
    'Marge 50%': '0,24€',
    'Base Impossable': '0,48€',
    '21%IVA': '0,10 €',
    'Preu Venta Públic': '0,58€',
  },
  {
    Referència: 'JC48',
    Descripció: 'BALLARI BOLA',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/381-498-ballari-bola.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/689-technology_large_default/ballari-bola.jpg',
    'preu major': '0,42€',
    'Marge 50%': '0,42€',
    'Base Impossable': '0,84€',
    '21%IVA': '0,18 €',
    'Preu Venta Públic': '1,02€',
  },
  {
    Referència: 'JC09',
    Descripció: 'Ballarí clàssic boix 40mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/386-501-ballari-classic-boix.html#/182-mida-28mm_o',
    Imàtges:
      'https://can-cels.com/692-technology_large_default/ballari-classic-boix.jpg',
    'preu major': '0,27€',
    'Marge 50%': '0,27€',
    'Base Impossable': '0,54€',
    '21%IVA': '0,11 €',
    'Preu Venta Públic': '0,65€',
  },
  {
    Referència: 'JC10',
    Descripció: 'BALLARI FAIG COLOR TIPO CLÀSSIC 40mm',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/382-497-ballari-faig-color-tipo-classic.html#/153-mida-40_mm_o',
    Imàtges:
      'https://can-cels.com/690-technology_large_default/ballari-faig-color-tipo-classic.jpg',
    'preu major': '0,28€',
    'Marge 50%': '0,28€',
    'Base Impossable': '0,56€',
    '21%IVA': '0,12 €',
    'Preu Venta Públic': '0,68€',
  },
  {
    Referència: 'JD06',
    Descripció: 'Ballarí saturn',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/389-504-ballari-saturn.html#/185-mida-48mm_o_79_mm',
    Imàtges:
      'https://can-cels.com/881-technology_large_default/ballari-saturn.jpg',
    'preu major': '1,25€',
    'Marge 50%': '1,25€',
    'Base Impossable': '2,50€',
    '21%IVA': '0,53 €',
    'Preu Venta Públic': '3,03€',
  },
  {
    Referència: 'TI02',
    Descripció: 'Baqueta de faig',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/576-613-baqueta-de-faig.html#/62-mida-20_cm',
    Imàtges:
      'https://can-cels.com/842-technology_large_default/baqueta-de-faig.jpg',
    'preu major': '0,64€',
    'Marge 50%': '0,32€',
    'Base Impossable': '0,96€',
    '21%IVA': '0,20 €',
    'Preu Venta Públic': '1,16€',
  },
  {
    Referència: 'JC46',
    Descripció: 'Base amb ballarins boix',
    Categoria: 'Baldufes',
    link: 'https://can-cels.com/ca/inici/703-base-amb-ballarins-boix.html',
    Imàtges:
      'https://can-cels.com/1030-technology_large_default/base-amb-ballarins-boix.jpg',
    'preu major': '2,57€',
    'Marge 50%': '1,29€',
    'Base Impossable': '3,86€',
    '21%IVA': '0,81 €',
    'Preu Venta Públic': '4,66€',
  },
  {
    Referència: 'TI05',
    Descripció: "Bastó cònic d'alzina",
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/568-601-basto-conic-d-alzina.html#/229-mida-42_cm_largo_oinf_30mm_x_osup_42mm',
    Imàtges:
      'https://can-cels.com/835-technology_large_default/basto-conic-d-alzina.jpg',
    'preu major': '4,20€',
    'Marge 50%': '2,10€',
    'Base Impossable': '6,30€',
    '21%IVA': '1,32 €',
    'Preu Venta Públic': '7,62€',
  },
  {
    Referència: 'JD94',
    Descripció: 'Blocs arquitectura colors',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/532-579-blocs-arquitectura-colors.html#/46-color-natural',
    Imàtges:
      'https://can-cels.com/803-technology_large_default/blocs-arquitectura-colors.jpg',
    'preu major': '13,91€',
    'Marge 50%': '6,96€',
    'Base Impossable': '20,87€',
    '21%IVA': '4,38 €',
    'Preu Venta Públic': '25,25€',
  },
  {
    Referència: 'JC24',
    Descripció: 'Blocs arquitectura colors',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/531-577-blocs-arquitectura-colors.html#/222-mida-32_x_18_x_5',
    Imàtges:
      'https://can-cels.com/802-technology_large_default/blocs-arquitectura-colors.jpg',
    'preu major': '10,50€',
    'Marge 50%': '5,25€',
    'Base Impossable': '15,75€',
    '21%IVA': '3,31 €',
    'Preu Venta Públic': '19,06€',
  },
  {
    Referència: 'XE16',
    Descripció: 'Boixet 10cm',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/664-boixet-10cm.html',
    Imàtges:
      'https://can-cels.com/945-technology_large_default/boixet-10cm.jpg',
    'preu major': '0,80€',
    'Marge 50%': '0,40€',
    'Base Impossable': '1,20€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,45€',
  },
  {
    Referència: 'XE02',
    Descripció: 'Boixet 5 cm',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/720-boixet-5-cm.html',
    Imàtges:
      'https://can-cels.com/1054-technology_large_default/boixet-5-cm.jpg',
    'preu major': '0,20€',
    'Marge 50%': '0,16€',
    'Base Impossable': '0,36€',
    '21%IVA': '0,08 €',
    'Preu Venta Públic': '0,44€',
  },
  {
    Referència: 'XE15',
    Descripció: 'Boixet formes 10cm',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/662-boixet-formes-10cm.html',
    Imàtges:
      'https://can-cels.com/943-technology_large_default/boixet-formes-10cm.jpg',
    'preu major': '0,80€',
    'Marge 50%': '0,40€',
    'Base Impossable': '1,20€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,45€',
  },
  {
    Referència: 'XE08',
    Descripció: 'Boixet gallec',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/647-707-boixet-gallec.html#/161-mida-11_cm',
    Imàtges:
      'https://can-cels.com/938-technology_large_default/boixet-gallec.jpg',
    'preu major': '0,32€',
    'Marge 50%': '0,16€',
    'Base Impossable': '0,48€',
    '21%IVA': '0,10 €',
    'Preu Venta Públic': '0,58€',
  },
  {
    Referència: 'XE01',
    Descripció: 'Boixet mini',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/660-boixet-mini.html',
    Imàtges:
      'https://can-cels.com/941-technology_large_default/boixet-mini.jpg',
    'preu major': '0,20€',
    'Marge 50%': '0,16€',
    'Base Impossable': '0,36€',
    '21%IVA': '0,08 €',
    'Preu Venta Públic': '0,44€',
  },
  {
    Referència: 'XE38',
    Descripció: 'Boixet prim',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/646-705-boixet-prim.html#/90-mida-10_cm',
    Imàtges:
      'https://can-cels.com/940-technology_large_default/boixet-prim.jpg',
    'preu major': '0,45€',
    'Marge 50%': '0,23€',
    'Base Impossable': '0,68€',
    '21%IVA': '0,14 €',
    'Preu Venta Públic': '0,82€',
  },
  {
    Referència: 'OL40',
    Descripció: 'Bola de faig  30mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,16€',
    'Marge 50%': '0,14€',
    'Base Impossable': '0,30€',
    '21%IVA': '0,06 €',
    'Preu Venta Públic': '0,36€',
  },
  {
    Referència: 'OL35',
    Descripció: 'Bola de faig 10mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,06€',
    'Marge 50%': '0,06€',
    'Base Impossable': '0,12€',
    '21%IVA': '0,03 €',
    'Preu Venta Públic': '0,15€',
  },
  {
    Referència: 'OL36',
    Descripció: 'Bola de faig 15mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,08€',
    'Marge 50%': '0,07€',
    'Base Impossable': '0,15€',
    '21%IVA': '0,03 €',
    'Preu Venta Públic': '0,18€',
  },
  {
    Referència: 'OL37',
    Descripció: 'Bola de faig 18mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,09€',
    'Marge 50%': '0,08€',
    'Base Impossable': '0,17€',
    '21%IVA': '0,04 €',
    'Preu Venta Públic': '0,20€',
  },
  {
    Referència: 'OL38',
    Descripció: 'Bola de faig 20mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,11€',
    'Marge 50%': '0,09€',
    'Base Impossable': '0,20€',
    '21%IVA': '0,04 €',
    'Preu Venta Públic': '0,25€',
  },
  {
    Referència: 'OL39',
    Descripció: 'Bola de faig 25mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,13€',
    'Marge 50%': '0,11€',
    'Base Impossable': '0,24€',
    '21%IVA': '0,05 €',
    'Preu Venta Públic': '0,29€',
  },
  {
    Referència: 'OL41',
    Descripció: 'Bola de faig 35mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/415-445-bola-de-faig.html#/152-mida-35mm_o',
    Imàtges:
      'https://can-cels.com/724-technology_large_default/bola-de-faig.jpg',
    'preu major': '0,18€',
    'Marge 50%': '0,15€',
    'Base Impossable': '0,33€',
    '21%IVA': '0,07 €',
    'Preu Venta Públic': '0,41€',
  },
  {
    Referència: 'CU107',
    Descripció: 'Bolet gran',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/420-464-bolet-petit-mitja-gran.html#/168-mida-23o_x_37mm',
    Imàtges:
      'https://can-cels.com/984-technology_large_default/bolet-petit-mitja-gran.jpg',
    'preu major': '0,94€',
    'Marge 50%': '0,47€',
    'Base Impossable': '1,41€',
    '21%IVA': '0,30 €',
    'Preu Venta Públic': '1,71€',
  },
  {
    Referència: 'CU106',
    Descripció: 'Bolet mitjà',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/420-464-bolet-petit-mitja-gran.html#/168-mida-23o_x_37mm',
    Imàtges:
      'https://can-cels.com/984-technology_large_default/bolet-petit-mitja-gran.jpg',
    'preu major': '0,27€',
    'Marge 50%': '0,27€',
    'Base Impossable': '0,54€',
    '21%IVA': '0,11 €',
    'Preu Venta Públic': '0,65€',
  },
  {
    Referència: 'CU105',
    Descripció: 'Bolet petit',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/420-464-bolet-petit-mitja-gran.html#/168-mida-23o_x_37mm',
    Imàtges:
      'https://can-cels.com/984-technology_large_default/bolet-petit-mitja-gran.jpg',
    'preu major': '0,17€',
    'Marge 50%': '0,17€',
    'Base Impossable': '0,34€',
    '21%IVA': '0,07 €',
    'Preu Venta Públic': '0,41€',
  },
  {
    Referència: 'tesoros',
    Descripció: 'Bossa cotó per als tresors',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/440-bossa-coto-per-als-tresors.html',
    Imàtges:
      'https://can-cels.com/861-technology_large_default/bossa-coto-per-als-tresors.jpg',
    'preu major': '1,05€',
    'Marge 50%': '0,53€',
    'Base Impossable': '1,58€',
    '21%IVA': '0,33 €',
    'Preu Venta Públic': '1,91€',
  },
  {
    Referència: 'Bossa',
    Descripció: 'Bossa de cotó',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/495-bossa-de-coto-.html',
    Imàtges:
      'https://can-cels.com/889-technology_large_default/bossa-de-coto-.jpg',
    'preu major': '1,00€',
    'Marge 50%': '0,50€',
    'Base Impossable': '1,50€',
    '21%IVA': '0,32 €',
    'Preu Venta Públic': '1,82€',
  },
  {
    Referència: 'XE99',
    Descripció: 'Botó',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/737-boto.html',
    Imàtges: 'https://can-cels.com/1064-technology_large_default/boto.jpg',
    'preu major': '0,50€',
    'Marge 50%': '0,25€',
    'Base Impossable': '0,75€',
    '21%IVA': '0,16 €',
    'Preu Venta Públic': '0,91€',
  },
  {
    Referència: 'DV31',
    Descripció: 'Botó',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/432-528-boto.html#/200-mida-55mmo_x_10mm',
    Imàtges: 'https://can-cels.com/870-technology_large_default/boto.jpg',
    'preu major': '0,37€',
    'Marge 50%': '0,19€',
    'Base Impossable': '0,56€',
    '21%IVA': '0,12 €',
    'Preu Venta Públic': '0,67€',
  },
  {
    Referència: 'JD88',
    Descripció: 'Botons sortit',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/736-botons-sortit.html',
    Imàtges:
      'https://can-cels.com/1053-technology_large_default/botons-sortit.jpg',
    'preu major': '3,68€',
    'Marge 50%': '1,84€',
    'Base Impossable': '5,52€',
    '21%IVA': '1,16 €',
    'Preu Venta Públic': '6,68€',
  },
  {
    Referència: 'JD112',
    Descripció: 'Braçalet mossegador',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/433-bracalet-mossegador.html',
    Imàtges:
      'https://can-cels.com/1005-technology_large_default/bracalet-mossegador.jpg',
    'preu major': '4,15€',
    'Marge 50%': '2,08€',
    'Base Impossable': '6,23€',
    '21%IVA': '1,31 €',
    'Preu Venta Públic': '7,53€',
  },
  {
    Referència: 'JC36',
    Descripció: 'Bufador',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/545-bufador.html',
    Imàtges: 'https://can-cels.com/817-technology_large_default/bufador.jpg',
    'preu major': '2,08€',
    'Marge 50%': '1,04€',
    'Base Impossable': '3,12€',
    '21%IVA': '0,66 €',
    'Preu Venta Públic': '3,78€',
  },
  {
    Referència: 'CA01',
    Descripció: 'Càmera de fotos',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/489-camera-de-fotos.html',
    Imàtges:
      'https://can-cels.com/770-technology_large_default/camera-de-fotos.jpg',
    'preu major': '2,99€',
    'Marge 50%': '1,50€',
    'Base Impossable': '4,49€',
    '21%IVA': '0,94 €',
    'Preu Venta Públic': '5,43€',
  },
  {
    Referència: 'JD21',
    Descripció: 'Carcaix amb 6 fletxes',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/549-585-carcaix-amb-6-fletxes.html#/225-mida-6_flechas',
    Imàtges:
      'https://can-cels.com/820-technology_large_default/carcaix-amb-6-fletxes.jpg',
    'preu major': '6,80€',
    'Marge 50%': '3,40€',
    'Base Impossable': '10,20€',
    '21%IVA': '2,14 €',
    'Preu Venta Públic': '12,34€',
  },
  {
    Referència: 'JC03',
    Descripció: 'Carraca',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/580-621-carraca.html#/241-mida-14x14cm',
    Imàtges: 'https://can-cels.com/846-technology_large_default/carraca.jpg',
    'preu major': '1,53€',
    'Marge 50%': '0,77€',
    'Base Impossable': '2,30€',
    '21%IVA': '0,48 €',
    'Preu Venta Públic': '2,78€',
  },
  {
    Referència: 'JC97',
    Descripció: 'Carraca assortit animals',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/584-623-carraca-assortit-animals.html#/243-mida-16x10cm',
    Imàtges:
      'https://can-cels.com/849-technology_large_default/carraca-assortit-animals.jpg',
    'preu major': '1,35€',
    'Marge 50%': '0,68€',
    'Base Impossable': '2,03€',
    '21%IVA': '0,43 €',
    'Preu Venta Públic': '2,45€',
  },
  {
    Referència: 'JC07',
    Descripció: 'Carraca gran',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/579-620-carraca-gran.html#/240-mida-26x12cm',
    Imàtges:
      'https://can-cels.com/845-technology_large_default/carraca-gran.jpg',
    'preu major': '5,68€',
    'Marge 50%': '2,84€',
    'Base Impossable': '8,52€',
    '21%IVA': '1,79 €',
    'Preu Venta Públic': '10,31€',
  },
  {
    Referència: 'JC37',
    Descripció: 'Carraca mini',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/581-622-carraca-mini.html#/242-mida-8x8cm',
    Imàtges:
      'https://can-cels.com/847-technology_large_default/carraca-mini.jpg',
    'preu major': '1,01€',
    'Marge 50%': '0,51€',
    'Base Impossable': '1,52€',
    '21%IVA': '0,32 €',
    'Preu Venta Públic': '1,83€',
  },
  {
    Referència: 'JD102',
    Descripció: 'Carraca mitjana colors',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/582-carraca-mitjana-colors.html',
    Imàtges:
      'https://can-cels.com/848-technology_large_default/carraca-mitjana-colors.jpg',
    'preu major': '2,10€',
    'Marge 50%': '1,05€',
    'Base Impossable': '3,15€',
    '21%IVA': '0,66 €',
    'Preu Venta Públic': '3,81€',
  },
  {
    Referència: 'JC69',
    Descripció: 'Castanyola',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/586-castanyola.html',
    Imàtges: 'https://can-cels.com/851-technology_large_default/castanyola.jpg',
    'preu major': '1,96€',
    'Marge 50%': '0,98€',
    'Base Impossable': '2,94€',
    '21%IVA': '0,62 €',
    'Preu Venta Públic': '3,56€',
  },
  {
    Referència: 'JC86',
    Descripció: 'Castanyoles amb mànec',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/575-607-castanyoles-amb-manec.html#/98-mida-13_cm',
    Imàtges:
      'https://can-cels.com/841-technology_large_default/castanyoles-amb-manec.jpg',
    'preu major': '1,05€',
    'Marge 50%': '0,53€',
    'Base Impossable': '1,58€',
    '21%IVA': '0,33 €',
    'Preu Venta Públic': '1,91€',
  },
  {
    Referència: 'JC30',
    Descripció: 'Castell de colors',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/533-580-castell-de-colors.html#/224-mida-31_x_11_cm',
    Imàtges:
      'https://can-cels.com/804-technology_large_default/castell-de-colors.jpg',
    'preu major': '10,72€',
    'Marge 50%': '5,36€',
    'Base Impossable': '16,08€',
    '21%IVA': '3,38 €',
    'Preu Venta Públic': '19,46€',
  },
  {
    Referència: 'JC74',
    Descripció: 'Cloc Cloc',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/670-cloc-cloc.html',
    Imàtges: 'https://can-cels.com/951-technology_large_default/cloc-cloc.jpg',
    'preu major': '0,68€',
    'Marge 50%': '0,34€',
    'Base Impossable': '1,02€',
    '21%IVA': '0,21 €',
    'Preu Venta Públic': '1,23€',
  },
  {
    Referència: 'JC33',
    Descripció: 'Cloc-cloc gran',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/518-564-cloc-cloc-gran.html#/103-mida-28_cm',
    Imàtges:
      'https://can-cels.com/790-technology_large_default/cloc-cloc-gran.jpg',
    'preu major': '1,61€',
    'Marge 50%': '0,81€',
    'Base Impossable': '2,42€',
    '21%IVA': '0,51 €',
    'Preu Venta Públic': '2,92€',
  },
  {
    Referència: 'JC74',
    Descripció: 'Cloc-cloc mini',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/519-566-cloc-cloc-mini.html#/51-mida-12_cm',
    Imàtges:
      'https://can-cels.com/973-technology_large_default/conjunt-morter.jpg',
    'preu major': '0,68€',
    'Marge 50%': '0,34€',
    'Base Impossable': '1,02€',
    '21%IVA': '0,21 €',
    'Preu Venta Públic': '1,23€',
  },
  {
    Referència: 'CU21',
    Descripció: 'Conjunt morter',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/692-conjunt-morter.html',
    Imàtges:
      'https://can-cels.com/791-technology_large_default/cloc-cloc-mini.jpg',
    'preu major': '0,36€',
    'Marge 50%': '0,47€',
    'Base Impossable': '0,83€',
    '21%IVA': '0,17 €',
    'Preu Venta Públic': '1,00€',
  },
  {
    Referència: 'JD85',
    Descripció: 'Corda animals assortits Petit',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/524-572-corda-animals-assortits-petit.html#/246-mida-pequena',
    Imàtges:
      'https://can-cels.com/797-technology_large_default/corda-animals-assortits-petit.jpg',
    'preu major': '1,38€',
    'Marge 50%': '0,69€',
    'Base Impossable': '2,07€',
    '21%IVA': '0,43 €',
    'Preu Venta Públic': '2,50€',
  },
  {
    Referència: 'JC64',
    Descripció: 'CORDA ANIMALS GRAN 14cm',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/680-corda-animals-gran.html',
    Imàtges:
      'https://can-cels.com/998-technology_large_default/corda-animals-gran.jpg',
    'preu major': '1,55€',
    'Marge 50%': '0,78€',
    'Base Impossable': '2,33€',
    '21%IVA': '0,49 €',
    'Preu Venta Públic': '2,81€',
  },
  {
    Referència: 'JC18',
    Descripció: 'Corda de saltar 2cm',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/520-567-corda-de-saltar.html#/244-mida-2_cm',
    Imàtges:
      'https://can-cels.com/792-technology_large_default/corda-de-saltar.jpg',
    'preu major': '0,77€',
    'Marge 50%': '0,39€',
    'Base Impossable': '1,16€',
    '21%IVA': '0,24 €',
    'Preu Venta Públic': '1,40€',
  },
  {
    Referència: 'JC19',
    Descripció: 'Corda de saltar amb timbre 2cm',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/521-568-corda-de-saltar-amb-timbre.html#/244-mida-2_cm',
    Imàtges:
      'https://can-cels.com/793-technology_large_default/corda-de-saltar-amb-timbre.jpg',
    'preu major': '1,54€',
    'Marge 50%': '0,77€',
    'Base Impossable': '2,31€',
    '21%IVA': '0,49 €',
    'Preu Venta Públic': '2,80€',
  },
  {
    Referència: 'JD101',
    Descripció: 'Corda de saltar cotó natural',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/522-corda-de-saltar-coto-natural.html',
    Imàtges:
      'https://can-cels.com/794-technology_large_default/corda-de-saltar-coto-natural.jpg',
    'preu major': '1,85€',
    'Marge 50%': '0,93€',
    'Base Impossable': '2,78€',
    '21%IVA': '0,58 €',
    'Preu Venta Públic': '3,36€',
  },
  {
    Referència: 'JC06',
    Descripció: 'Corda de saltar de rosca',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/523-570-corda-de-saltar-de-rosca.html#/218-mida-4_cm',
    Imàtges:
      'https://can-cels.com/795-technology_large_default/corda-de-saltar-de-rosca.jpg',
    'preu major': '2,59€',
    'Marge 50%': '1,30€',
    'Base Impossable': '3,89€',
    '21%IVA': '0,82 €',
    'Preu Venta Públic': '4,70€',
  },
  {
    Referència: 'JD87',
    Descripció: 'Cotxe policia, grua o camió bombers',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/498-cotxe-policia-grua-o-camio-bombers.html',
    Imàtges:
      'https://can-cels.com/773-technology_large_default/cotxe-policia-grua-o-camio-bombers.jpg',
    'preu major': '2,86€',
    'Marge 50%': '1,43€',
    'Base Impossable': '4,29€',
    '21%IVA': '0,90 €',
    'Preu Venta Públic': '5,19€',
  },
  {
    Referència: 'JD31',
    Descripció: 'Cotxes assortits',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/499-cotxes-assortits.html',
    Imàtges:
      'https://can-cels.com/774-technology_large_default/cotxes-assortits.jpg',
    'preu major': '1,93€',
    'Marge 50%': '0,97€',
    'Base Impossable': '2,90€',
    '21%IVA': '0,61 €',
    'Preu Venta Públic': '3,50€',
  },
  {
    Referència: 'JD73',
    Descripció: 'Creu del diable',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/711-creu-del-diable.html',
    Imàtges:
      'https://can-cels.com/1039-technology_large_default/creu-del-diable.jpg',
    'preu major': '3,26€',
    'Marge 50%': '1,63€',
    'Base Impossable': '4,89€',
    '21%IVA': '1,03 €',
    'Preu Venta Públic': '5,92€',
  },
  {
    Referència: 'JC79',
    Descripció: 'Cub serp puzle 3D',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/540-cub-serp-puzle-3d.html',
    Imàtges:
      'https://can-cels.com/812-technology_large_default/cub-serp-puzle-3d.jpg',
    'preu major': '4,14€',
    'Marge 50%': '2,07€',
    'Base Impossable': '6,21€',
    '21%IVA': '1,30 €',
    'Preu Venta Públic': '7,51€',
  },
  {
    Referència: 'JD107',
    Descripció: 'CUBILET',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/436-532-cubilet.html#/202-mida-47ox60',
    Imàtges: 'https://can-cels.com/723-technology_large_default/cubilet.jpg',
    'preu major': '1,05€',
    'Marge 50%': '0,53€',
    'Base Impossable': '1,58€',
    '21%IVA': '0,33 €',
    'Preu Venta Públic': '1,91€',
  },
  {
    Referència: 'JD100',
    Descripció: 'Cuc de colors articulat',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/476-cuc-de-colors-articulat.html',
    Imàtges:
      'https://can-cels.com/759-technology_large_default/cuc-de-colors-articulat.jpg',
    'preu major': '1,59€',
    'Marge 50%': '0,80€',
    'Base Impossable': '2,39€',
    '21%IVA': '0,50 €',
    'Preu Venta Públic': '2,89€',
  },
  {
    Referència: 'CU03',
    Descripció: 'Cullera de faig 10cm',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/633-688-cullera-de-faig.html#/89-mida-22_cm',
    Imàtges:
      'https://can-cels.com/964-technology_large_default/cullera-de-faig.jpg',
    'preu major': '0,27€',
    'Marge 50%': '0,14€',
    'Base Impossable': '0,41€',
    '21%IVA': '0,09 €',
    'Preu Venta Públic': '0,49€',
  },
  {
    Referència: 'CU17',
    Descripció: 'Culleres per la mel de boix 11cm',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/estris-de-cuina/638-698-culleres-per-la-mel-de-boix.html#/161-mida-11_cm',
    Imàtges:
      'https://can-cels.com/965-technology_large_default/culleres-per-la-mel-de-boix.jpg',
    'preu major': '0,28€',
    'Marge 50%': '0,14€',
    'Base Impossable': '0,42€',
    '21%IVA': '0,09 €',
    'Preu Venta Públic': '0,51€',
  },
  {
    Referència: 'CU30',
    Descripció: "Cullerot d'olives de faig",
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/627-675-cullerot-d-olives-de-faig.html#/263-mida-5_cm_boca',
    Imàtges:
      'https://can-cels.com/926-technology_large_default/cullerot-d-olives-de-faig.jpg',
    'preu major': '1,97€',
    'Marge 50%': '0,99€',
    'Base Impossable': '2,96€',
    '21%IVA': '0,62 €',
    'Preu Venta Públic': '3,58€',
  },
  {
    Referència: 'JC20',
    Descripció: 'Diàbol M eix de fusta',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/529-575-diabol-m-eix-de-fusta.html#/221-mida-varilla_415_diabolo_115x95',
    Imàtges:
      'https://can-cels.com/800-technology_large_default/diabol-m-eix-de-fusta.jpg',
    'preu major': '4,86€',
    'Marge 50%': '2,43€',
    'Base Impossable': '7,29€',
    '21%IVA': '1,53 €',
    'Preu Venta Públic': '8,82€',
  },
  {
    Referència: 'JC20',
    Descripció: 'Diàbolo petit',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/527-574-diabolo-petit.html#/220-mida-varilla_335_diabolo_9x7',
    Imàtges:
      'https://can-cels.com/799-technology_large_default/diabolo-petit.jpg',
    'preu major': '1,58€',
    'Marge 50%': '0,79€',
    'Base Impossable': '2,37€',
    '21%IVA': '0,50 €',
    'Preu Venta Públic': '2,87€',
  },
  {
    Referència: 'XE29',
    Descripció: 'Didal de boix',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/671-didal-de-boix.html',
    Imàtges:
      'https://can-cels.com/952-technology_large_default/didal-de-boix.jpg',
    'preu major': '0,35€',
    'Marge 50%': '0,23€',
    'Base Impossable': '0,58€',
    '21%IVA': '0,12 €',
    'Preu Venta Públic': '0,70€',
  },
  {
    Referència: 'XE30',
    Descripció: 'Didal de boix colors',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/726-didal-de-boix-colors.html',
    Imàtges:
      'https://can-cels.com/1049-technology_large_default/didal-de-faig.jpg',
    'preu major': '0,42€',
    'Marge 50%': '0,25€',
    'Base Impossable': '0,67€',
    '21%IVA': '0,14 €',
    'Preu Venta Públic': '0,81€',
  },
  {
    Referència: 'XE36',
    Descripció: 'Didal de faig',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/727-didal-de-faig.html',
    Imàtges:
      'https://can-cels.com/1048-technology_large_default/didal-de-boix-colors.jpg',
    'preu major': '0,18€',
    'Marge 50%': '0,23€',
    'Base Impossable': '0,41€',
    '21%IVA': '0,09 €',
    'Preu Venta Públic': '0,50€',
  },
  {
    Referència: 'DV32',
    Descripció: 'Discos interconectats',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/422-discos-interconectats.html',
    Imàtges:
      'https://can-cels.com/982-technology_large_default/discos-interconectats.jpg',
    'preu major': '0,92€',
    'Marge 50%': '0,92€',
    'Base Impossable': '1,84€',
    '21%IVA': '0,39 €',
    'Preu Venta Públic': '2,23€',
  },
  {
    Referència: 'JC23F',
    Descripció: 'Dòmino animals',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/396-520-domino-animals.html#/196-mida-70_x35_x_7_cm',
    Imàtges:
      'https://can-cels.com/963-technology_large_default/domino-animals.jpg',
    'preu major': '10,45€',
    'Marge 50%': '5,23€',
    'Base Impossable': '15,68€',
    '21%IVA': '3,29 €',
    'Preu Venta Públic': '18,97€',
  },
  {
    Referència: 'JC23D',
    Descripció: 'Dòmino Can Cels',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/403-524-domino-can-cels.html#/196-mida-70_x35_x_7_cm',
    Imàtges:
      'https://can-cels.com/991-technology_large_default/domino-can-cels.jpg',
    'preu major': '6,30€',
    'Marge 50%': '3,15€',
    'Base Impossable': '9,45€',
    '21%IVA': '1,98 €',
    'Preu Venta Públic': '11,43€',
  },
  {
    Referència: 'JC23E',
    Descripció: 'Dòmino formes colors',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/402-523-domino-formes-colors.html#/196-mida-70_x35_x_7_cm',
    Imàtges:
      'https://can-cels.com/706-technology_large_default/domino-formes-colors.jpg',
    'preu major': '8,95€',
    'Marge 50%': '4,48€',
    'Base Impossable': '13,43€',
    '21%IVA': '2,82 €',
    'Preu Venta Públic': '16,24€',
  },
  {
    Referència: 'JC23C',
    Descripció: 'Dòmino fruites',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/397-521-domino-fruites.html#/196-mida-70_x35_x_7_cm',
    Imàtges:
      'https://can-cels.com/702-technology_large_default/domino-fruites.jpg',
    'preu major': '6,30€',
    'Marge 50%': '3,15€',
    'Base Impossable': '9,45€',
    '21%IVA': '1,98 €',
    'Preu Venta Públic': '11,43€',
  },
  {
    Referència: 'JC23B',
    Descripció: 'Dòmino punts',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/395-519-domino-punts.html#/196-mida-70_x35_x_7_cm',
    Imàtges:
      'https://can-cels.com/700-technology_large_default/domino-punts.jpg',
    'preu major': '8,95€',
    'Marge 50%': '4,48€',
    'Base Impossable': '13,43€',
    '21%IVA': '2,82 €',
    'Preu Venta Públic': '16,24€',
  },
  {
    Referència: 'JC23A',
    Descripció: 'Dòmino rodones de colors',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/401-522-domino-rodones-de-colors.html#/196-mida-70_x35_x_7_cm',
    Imàtges:
      'https://can-cels.com/875-technology_large_default/domino-rodones-de-colors.jpg',
    'preu major': '8,95€',
    'Marge 50%': '4,48€',
    'Base Impossable': '13,43€',
    '21%IVA': '2,82 €',
    'Preu Venta Públic': '16,24€',
  },
  {
    Referència: 'JD104',
    Descripció: 'El tió amb rodes',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/442-536-el-tio-amb-rodes.html#/209-mida-24_cm',
    Imàtges:
      'https://can-cels.com/727-technology_large_default/el-tio-amb-rodes.jpg',
    'preu major': '14,77€',
    'Marge 50%': '7,39€',
    'Base Impossable': '22,16€',
    '21%IVA': '4,65 €',
    'Preu Venta Públic': '26,81€',
  },
  {
    Referència: 'JD108',
    Descripció: 'El Tió amb rodes petit',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/441-535-el-tio-amb-rodes-petit.html#/90-mida-10_cm',
    Imàtges:
      'https://can-cels.com/726-technology_large_default/el-tio-amb-rodes-petit.jpg',
    'preu major': '5,24€',
    'Marge 50%': '2,62€',
    'Base Impossable': '7,86€',
    '21%IVA': '1,65 €',
    'Preu Venta Públic': '9,51€',
  },
  {
    Referència: 'TM3904',
    Descripció: 'Empassa boles',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/546-empassa-boles-.html',
    Imàtges:
      'https://can-cels.com/818-technology_large_default/empassa-boles-.jpg',
    'preu major': '28,35€',
    'Marge 50%': '14,18€',
    'Base Impossable': '42,53€',
    '21%IVA': '8,93 €',
    'Preu Venta Públic': '51,46€',
  },
  {
    Referència: 'JD43',
    Descripció: 'Encaix boles',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/485-544-encaix-boles.html#/207-mida-23_cm',
    Imàtges:
      'https://can-cels.com/767-technology_large_default/encaix-boles.jpg',
    'preu major': '4,99€',
    'Marge 50%': '2,50€',
    'Base Impossable': '7,49€',
    '21%IVA': '1,57 €',
    'Preu Venta Públic': '9,06€',
  },
  {
    Referència: 'JD44',
    Descripció: 'Encaix de cilindres',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/484-543-encaix-de-cilindres.html#/91-mida-175_cm',
    Imàtges:
      'https://can-cels.com/962-technology_large_default/encaix-de-cilindres.jpg',
    'preu major': '5,07€',
    'Marge 50%': '2,54€',
    'Base Impossable': '7,61€',
    '21%IVA': '1,60 €',
    'Preu Venta Públic': '9,20€',
  },
  {
    Referència: 'JD45',
    Descripció: 'Encaix de cubs',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/486-545-encaix-de-cubs.html#/208-mida-275_cm',
    Imàtges:
      'https://can-cels.com/768-technology_large_default/encaix-de-cubs.jpg',
    'preu major': '5,38€',
    'Marge 50%': '2,69€',
    'Base Impossable': '8,07€',
    '21%IVA': '1,69 €',
    'Preu Venta Públic': '9,76€',
  },
  {
    Referència: 'JC02',
    Descripció: 'ESCALADOR',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/547-escalador.html',
    Imàtges: 'https://can-cels.com/819-technology_large_default/escalador.jpg',
    'preu major': '2,13€',
    'Marge 50%': '1,07€',
    'Base Impossable': '3,20€',
    '21%IVA': '0,67 €',
    'Preu Venta Públic': '3,87€',
  },
  {
    Referència: 'JC66',
    Descripció: 'Espasa corsari',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/501-553-espasa-corsari.html#/211-mida-54_cm',
    Imàtges:
      'https://can-cels.com/776-technology_large_default/espasa-corsari.jpg',
    'preu major': '2,36€',
    'Marge 50%': '2,36€',
    'Base Impossable': '4,72€',
    '21%IVA': '0,99 €',
    'Preu Venta Públic': '5,71€',
  },
  {
    Referència: 'JC65',
    Descripció: 'Espasa recta',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/502-554-espasa-recta.html#/212-mida-57_cm',
    Imàtges:
      'https://can-cels.com/777-technology_large_default/espasa-recta.jpg',
    'preu major': '1,70€',
    'Marge 50%': '1,70€',
    'Base Impossable': '3,40€',
    '21%IVA': '0,71 €',
    'Preu Venta Públic': '4,11€',
  },
  {
    Referència: 'JC91',
    Descripció: 'Espasa recta a foc',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/503-555-espasa-recta-a-foc.html#/212-mida-57_cm',
    Imàtges:
      'https://can-cels.com/778-technology_large_default/espasa-recta-a-foc.jpg',
    'preu major': '1,28€',
    'Marge 50%': '0,64€',
    'Base Impossable': '1,92€',
    '21%IVA': '0,40 €',
    'Preu Venta Públic': '2,32€',
  },
  {
    Referència: 'CU116',
    Descripció: 'Espàtula de faig',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/631-683-espatula-de-faig.html#/62-mida-20_cm',
    Imàtges:
      'https://can-cels.com/1036-technology_large_default/espatula-de-faig.jpg',
    'preu major': '0,44€',
    'Marge 50%': '0,22€',
    'Base Impossable': '0,66€',
    '21%IVA': '0,14 €',
    'Preu Venta Públic': '0,80€',
  },
  {
    Referència: 'JD105',
    Descripció: 'Estrella xinesa',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/398-510-estrella-xinesa.html#/191-mida-35cm',
    Imàtges:
      'https://can-cels.com/703-technology_large_default/estrella-xinesa.jpg',
    'preu major': '14,72€',
    'Marge 50%': '7,36€',
    'Base Impossable': '22,08€',
    '21%IVA': '4,64 €',
    'Preu Venta Públic': '26,72€',
  },
  {
    Referència: 'JC84',
    Descripció: 'Flauta decorada assortida',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/585-624-flauta-decorada-assortida.html#/71-mida-32_cm',
    Imàtges:
      'https://can-cels.com/850-technology_large_default/flauta-decorada-assortida.jpg',
    'preu major': '3,22€',
    'Marge 50%': '1,61€',
    'Base Impossable': '4,83€',
    '21%IVA': '1,01 €',
    'Preu Venta Públic': '5,84€',
  },
  {
    Referència: 'JD64',
    Descripció: 'FLAUTA PITO PASTOR',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/679-flauta-pito-pastor.html',
    Imàtges:
      'https://can-cels.com/993-technology_large_default/flauta-pito-pastor.jpg',
    'preu major': '0,90€',
    'Marge 50%': '0,45€',
    'Base Impossable': '1,35€',
    '21%IVA': '0,28 €',
    'Preu Venta Públic': '1,63€',
  },
  {
    Referència: 'JD55',
    Descripció: 'Floret gran o petit',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/504-557-floret-gran-o-petit.html#/106-mida-50_cm',
    Imàtges:
      'https://can-cels.com/779-technology_large_default/floret-gran-o-petit.jpg',
    'preu major': '1,05€',
    'Marge 50%': '0,53€',
    'Base Impossable': '1,58€',
    '21%IVA': '0,33 €',
    'Preu Venta Públic': '1,91€',
  },
  {
    Referència: 'GA01',
    Descripció: 'Galeta Maria',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/434-530-galeta-maria.html#/200-mida-55mmo_x_10mm',
    Imàtges:
      'https://can-cels.com/1000-technology_large_default/galeta-maria.jpg',
    'preu major': '1,03€',
    'Marge 50%': '0,52€',
    'Base Impossable': '1,55€',
    '21%IVA': '0,32 €',
    'Preu Venta Públic': '1,87€',
  },
  {
    Referència: 'GA02',
    Descripció: 'Galeta Petit Beurre',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/435-531-galeta-petit-beurre.html#/201-mida-75mm_x_50_x_10mm',
    Imàtges:
      'https://can-cels.com/1001-technology_large_default/galeta-petit-beurre.jpg',
    'preu major': '1,08€',
    'Marge 50%': '0,54€',
    'Base Impossable': '1,62€',
    '21%IVA': '0,34 €',
    'Preu Venta Públic': '1,96€',
  },
  {
    Referència: 'XE45',
    Descripció: 'Ganxet',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/750-ganxet.html',
    Imàtges: 'https://can-cels.com/1060-technology_large_default/ganxet.jpg',
    'preu major': '1,48€',
    'Marge 50%': '0,74€',
    'Base Impossable': '2,22€',
    '21%IVA': '0,47 €',
    'Preu Venta Públic': '2,69€',
  },
  {
    Referència: 'XE72',
    Descripció: 'Ganxet',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/738-1063-ganxet.html#/295-mida-o_8_mm_x185_cm',
    Imàtges: 'https://can-cels.com/1066-technology_large_default/ganxet.jpg',
    'preu major': '2,73€',
    'Marge 50%': '1,37€',
    'Base Impossable': '4,10€',
    '21%IVA': '0,86 €',
    'Preu Venta Públic': '4,95€',
  },
  {
    Referència: 'XE85',
    Descripció: 'Ganxet',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/669-ganxet.html',
    Imàtges: 'https://can-cels.com/950-technology_large_default/ganxet.jpg',
    'preu major': '1,86€',
    'Marge 50%': '0,93€',
    'Base Impossable': '2,79€',
    '21%IVA': '0,59 €',
    'Preu Venta Públic': '3,38€',
  },
  {
    Referència: 'XE97',
    Descripció: 'Ganxet',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/744-1075-ganxet.html#/304-mida-o_5_mm_x20_cm',
    Imàtges: 'https://can-cels.com/1065-technology_large_default/ganxet.jpg',
    'preu major': '1,73€',
    'Marge 50%': '0,87€',
    'Base Impossable': '2,60€',
    '21%IVA': '0,54 €',
    'Preu Venta Públic': '3,14€',
  },
  {
    Referència: 'JD19',
    Descripció: 'Girafa desmuntable',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/488-girafa-desmuntable.html',
    Imàtges:
      'https://can-cels.com/769-technology_large_default/girafa-desmuntable.jpg',
    'preu major': '1,08€',
    'Marge 50%': '0,54€',
    'Base Impossable': '1,62€',
    '21%IVA': '0,34 €',
    'Preu Venta Públic': '1,96€',
  },
  {
    Referència: 'JD24',
    Descripció: 'Guardiola',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/514-guardiola.html',
    Imàtges: 'https://can-cels.com/787-technology_large_default/guardiola.jpg',
    'preu major': '1,97€',
    'Marge 50%': '0,99€',
    'Base Impossable': '2,96€',
    '21%IVA': '0,62 €',
    'Preu Venta Públic': '3,58€',
  },
  {
    Referència: 'JD92',
    Descripció: 'Harmònica',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/musica/572-harmonica.html',
    Imàtges: 'https://can-cels.com/839-technology_large_default/harmonica.jpg',
    'preu major': '2,30€',
    'Marge 50%': '1,15€',
    'Base Impossable': '3,45€',
    '21%IVA': '0,72 €',
    'Preu Venta Públic': '4,17€',
  },
  {
    Referència: 'JC63',
    Descripció: 'IO- IO ASSORTIT',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/536-io-io-assortit.html',
    Imàtges:
      'https://can-cels.com/807-technology_large_default/io-io-assortit.jpg',
    'preu major': '0,78€',
    'Marge 50%': '0,39€',
    'Base Impossable': '1,17€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,42€',
  },
  {
    Referència: 'JC11',
    Descripció: 'io-io',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/535-io-io.html',
    Imàtges: 'https://can-cels.com/806-technology_large_default/io-io.jpg',
    'preu major': '0,77€',
    'Marge 50%': '0,39€',
    'Base Impossable': '1,16€',
    '21%IVA': '0,24 €',
    'Preu Venta Públic': '1,40€',
  },
  {
    Referència: 'JD86',
    Descripció: 'io-io arrodonit',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/534-io-io-arrodonit.html',
    Imàtges:
      'https://can-cels.com/805-technology_large_default/io-io-arrodonit.jpg',
    'preu major': '0,92€',
    'Marge 50%': '0,46€',
    'Base Impossable': '1,38€',
    '21%IVA': '0,29 €',
    'Preu Venta Públic': '1,67€',
  },
  {
    Referència: 'JD86-2',
    Descripció: 'io-io marieta',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/538-io-io-marieta.html',
    Imàtges:
      'https://can-cels.com/810-technology_large_default/io-io-marieta.jpg',
    'preu major': '1,55€',
    'Marge 50%': '0,78€',
    'Base Impossable': '2,33€',
    '21%IVA': '0,49 €',
    'Preu Venta Públic': '2,81€',
  },
  {
    Referència: 'JC42',
    Descripció: 'io-io mini',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/537-io-io-mini.html',
    Imàtges: 'https://can-cels.com/809-technology_large_default/io-io-mini.jpg',
    'preu major': '0,40€',
    'Marge 50%': '0,20€',
    'Base Impossable': '0,60€',
    '21%IVA': '0,13 €',
    'Preu Venta Públic': '0,73€',
  },
  {
    Referència: 'TL26',
    Descripció: 'Joc de bitlles',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/556-591-joc-de-bitlles.html#/53-mida-26_cm',
    Imàtges:
      'https://can-cels.com/890-technology_large_default/joc-de-bitlles-35-cm.jpg',
    'preu major': '12,77€',
    'Marge 50%': '6,39€',
    'Base Impossable': '19,16€',
    '21%IVA': '4,02 €',
    'Preu Venta Públic': '23,18€',
  },
  {
    Referència: 'TL35',
    Descripció: 'Joc de bitlles 35 cm',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/555-588-joc-de-bitlles-35-cm.html#/191-mida-35cm',
    Imàtges:
      'https://can-cels.com/825-technology_large_default/joc-de-bitlles.jpg',
    'preu major': '22,36€',
    'Marge 50%': '11,18€',
    'Base Impossable': '33,54€',
    '21%IVA': '7,04 €',
    'Preu Venta Públic': '40,58€',
  },
  {
    Referència: 'TL40',
    Descripció: 'Joc de bitlles mini 7cm',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/563-598-joc-de-bitlles-mini.html#/227-mida-7_cm',
    Imàtges:
      'https://can-cels.com/832-technology_large_default/joc-de-bitlles-mini.jpg',
    'preu major': '2,40€',
    'Marge 50%': '1,20€',
    'Base Impossable': '3,60€',
    '21%IVA': '0,76 €',
    'Preu Venta Públic': '4,36€',
  },
  {
    Referència: 'TL60',
    Descripció: 'Joc de bitlles soldat',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/558-593-joc-de-bitlles-soldat.html#/53-mida-26_cm',
    Imàtges:
      'https://can-cels.com/827-technology_large_default/joc-de-bitlles-soldat.jpg',
    'preu major': '5,61€',
    'Marge 50%': '2,81€',
    'Base Impossable': '8,42€',
    '21%IVA': '1,77 €',
    'Preu Venta Públic': '10,18€',
  },
  {
    Referència: 'TL50',
    Descripció: 'Joc de boleres mini',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/562-597-joc-de-boleres-mini.html#/248-mida-55_cm',
    Imàtges:
      'https://can-cels.com/831-technology_large_default/joc-de-boleres-mini.jpg',
    'preu major': '2,14€',
    'Marge 50%': '1,07€',
    'Base Impossable': '3,21€',
    '21%IVA': '0,67 €',
    'Preu Venta Públic': '3,88€',
  },
  {
    Referència: 'JD03',
    Descripció: 'Joc de boleres ratllades',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/557-592-joc-de-boleres-ratllades.html#/53-mida-26_cm',
    Imàtges:
      'https://can-cels.com/826-technology_large_default/joc-de-boleres-ratllades.jpg',
    'preu major': '12,67€',
    'Marge 50%': '6,34€',
    'Base Impossable': '19,01€',
    '21%IVA': '3,99 €',
    'Preu Venta Públic': '23,00€',
  },
  {
    Referència: 'TL20',
    Descripció: 'Joc de boleres vermella',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/560-595-joc-de-boleres-vermella.html#/98-mida-13_cm',
    Imàtges:
      'https://can-cels.com/829-technology_large_default/joc-de-boleres-vermella.jpg',
    'preu major': '4,62€',
    'Marge 50%': '2,31€',
    'Base Impossable': '6,93€',
    '21%IVA': '1,46 €',
    'Preu Venta Públic': '8,39€',
  },
  {
    Referència: 'JC89',
    Descripció: 'Llapis assortit animals',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/714-1018-llapis-assortit-animals.html#/217-mida-36',
    Imàtges:
      'https://can-cels.com/1042-technology_large_default/llapis-assortit-animals.jpg',
    'preu major': '0,66€',
    'Marge 50%': '0,33€',
    'Base Impossable': '0,99€',
    '21%IVA': '0,21 €',
    'Preu Venta Públic': '1,20€',
  },
  {
    Referència: 'CU91',
    Descripció: 'LLaurador de boix 11cm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/416-454-llaurador-de-boix.html#/161-mida-11_cm',
    Imàtges:
      'https://can-cels.com/716-technology_large_default/llaurador-de-boix.jpg',
    'preu major': '1,12€',
    'Marge 50%': '0,56€',
    'Base Impossable': '1,68€',
    '21%IVA': '0,35 €',
    'Preu Venta Públic': '2,03€',
  },
  {
    Referència: 'CU00',
    Descripció: 'Mà de morter de faig 10cm',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/622-669-ma-de-morter-de-faig.html#/52-mida-19_cm',
    Imàtges:
      'https://can-cels.com/937-technology_large_default/ma-de-morter-de-faig.jpg',
    'preu major': '0,39€',
    'Marge 50%': '0,20€',
    'Base Impossable': '0,59€',
    '21%IVA': '0,12 €',
    'Preu Venta Públic': '0,71€',
  },
  {
    Referència: 'JC39',
    Descripció: 'MaletÍ de jocs tradicionals',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/516-maleti-de-jocs-tradicionals.html',
    Imàtges:
      'https://can-cels.com/788-technology_large_default/maleti-de-jocs-tradicionals.jpg',
    'preu major': '28,72€',
    'Marge 50%': '14,36€',
    'Base Impossable': '43,08€',
    '21%IVA': '9,05 €',
    'Preu Venta Públic': '52,13€',
  },
  {
    Referència: 'JC81',
    Descripció: 'Maquineta',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/508-maquineta.html',
    Imàtges: 'https://can-cels.com/782-technology_large_default/maquineta.jpg',
    'preu major': '0,60€',
    'Marge 50%': '0,30€',
    'Base Impossable': '0,90€',
    '21%IVA': '0,19 €',
    'Preu Venta Públic': '1,09€',
  },
  {
    Referència: 'JC85',
    Descripció: 'Maraques assortides',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/574-606-maraques-assortides.html#/137-mida-18_cm',
    Imàtges:
      'https://can-cels.com/840-technology_large_default/maraques-assortides.jpg',
    'preu major': '1,46€',
    'Marge 50%': '0,73€',
    'Base Impossable': '2,19€',
    '21%IVA': '0,46 €',
    'Preu Venta Públic': '2,65€',
  },
  {
    Referència: 'JD106',
    Descripció: 'Memòria animals',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/412-1007-memoria-animals.html#/198-mida-17_x_17_cm',
    Imàtges:
      'https://can-cels.com/979-technology_large_default/memoria-animals.jpg',
    'preu major': '8,65€',
    'Marge 50%': '4,33€',
    'Base Impossable': '12,98€',
    '21%IVA': '2,72 €',
    'Preu Venta Públic': '15,70€',
  },
  {
    Referència: 'JC17',
    Descripció: 'Mikado  petit 22cm',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/410-435-mikado-gran-o-petit.html#/89-mida-22_cm',
    Imàtges:
      'https://can-cels.com/712-technology_large_default/mikado-gran-o-petit.jpg',
    'preu major': '5,36€',
    'Marge 50%': '2,68€',
    'Base Impossable': '8,04€',
    '21%IVA': '1,69 €',
    'Preu Venta Públic': '9,73€',
  },
  {
    Referència: 'JC89',
    Descripció: 'Mikado gran 33cm',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/715-1019-mini-premsa-flors.html#/217-mida-36',
    Imàtges:
      'https://can-cels.com/1043-technology_large_default/mini-premsa-flors.jpg',
    'preu major': '6,77€',
    'Marge 50%': '3,39€',
    'Base Impossable': '10,16€',
    '21%IVA': '2,13 €',
    'Preu Venta Públic': '12,29€',
  },
  {
    Referència: 'JC76',
    Descripció: 'Mini premsa flors',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/jocs-d-habilitat/659-mobil-assortit-molla.html',
    Imàtges:
      'https://can-cels.com/917-technology_large_default/mobil-assortit-molla.jpg',
    'preu major': '6,36€',
    'Marge 50%': '3,18€',
    'Base Impossable': '9,54€',
    '21%IVA': '2,00 €',
    'Preu Venta Públic': '11,54€',
  },
  {
    Referència: 'JC77',
    Descripció: 'MÒBIL ASSORTIT MOLLA',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/543-mobil-corda-animals-assortits.html',
    Imàtges:
      'https://can-cels.com/815-technology_large_default/mobil-corda-animals-assortits.jpg',
    'preu major': '1,31€',
    'Marge 50%': '0,66€',
    'Base Impossable': '1,97€',
    '21%IVA': '0,41 €',
    'Preu Venta Públic': '2,38€',
  },
  {
    Referència: 'JD27',
    Descripció: 'Mòbil corda animals assortits',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/542-581-mobil-corda-pinotxo.html#/51-mida-12_cm',
    Imàtges:
      'https://can-cels.com/814-technology_large_default/mobil-corda-pinotxo.jpg',
    'preu major': '1,25€',
    'Marge 50%': '0,63€',
    'Base Impossable': '1,88€',
    '21%IVA': '0,39 €',
    'Preu Venta Públic': '2,27€',
  },
  {
    Referència: 'JC103',
    Descripció: 'Mòbil corda Pinotxo',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/708-mobil-mirallpissarra.html',
    Imàtges:
      'https://can-cels.com/1082-technology_large_default/mobil-mirallpissarra.jpg',
    'preu major': '0,80€',
    'Marge 50%': '0,40€',
    'Base Impossable': '1,20€',
    '21%IVA': '0,25 €',
    'Preu Venta Públic': '1,45€',
  },
  {
    Referència: 'CU22',
    Descripció: 'Morter',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/493-549-morter.html#/210-mida-o_45cm',
    Imàtges: 'https://can-cels.com/866-technology_large_default/morter.jpg',
    'preu major': '0,83€',
    'Marge 50%': '0,42€',
    'Base Impossable': '1,25€',
    '21%IVA': '0,26 €',
    'Preu Venta Públic': '1,51€',
  },
  {
    Referència: 'JC49',
    Descripció: 'Ocells fusters',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/513-ocells-fusters.html',
    Imàtges:
      'https://can-cels.com/786-technology_large_default/ocells-fusters.jpg',
    'preu major': '6,64€',
    'Marge 50%': '3,32€',
    'Base Impossable': '9,96€',
    '21%IVA': '2,09 €',
    'Preu Venta Públic': '12,05€',
  },
  {
    Referència: 'CU13',
    Descripció: 'Ou de faig 36mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/419-462-ou-de-faig.html#/166-mida-36mm_o',
    Imàtges: 'https://can-cels.com/980-technology_large_default/ou-de-faig.jpg',
    'preu major': '0,24€',
    'Marge 50%': '0,12€',
    'Base Impossable': '0,36€',
    '21%IVA': '0,08 €',
    'Preu Venta Públic': '0,44€',
  },
  {
    Referència: 'CU10',
    Descripció: 'Ou de faig gran 5cm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/730-ou-de-faig-gran.html',
    Imàtges:
      'https://can-cels.com/1047-technology_large_default/ou-de-faig-gran.jpg',
    'preu major': '0,46€',
    'Marge 50%': '0,23€',
    'Base Impossable': '0,69€',
    '21%IVA': '0,14 €',
    'Preu Venta Públic': '0,83€',
  },
  {
    Referència: 'CU13',
    Descripció: 'Ou de faig petit 5cm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/731-ou-de-faig-petit.html',
    Imàtges:
      'https://can-cels.com/1076-technology_large_default/ou-de-faig-petit.jpg',
    'preu major': '0,24€',
    'Marge 50%': '0,12€',
    'Base Impossable': '0,36€',
    '21%IVA': '0,08 €',
    'Preu Venta Públic': '0,44€',
  },
  {
    Referència: 'CU11',
    Descripció: 'Ou gran boixet 5cm',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/728-ou-gran.html',
    Imàtges: 'https://can-cels.com/1045-technology_large_default/ou-gran.jpg',
    'preu major': '0,84€',
    'Marge 50%': '0,42€',
    'Base Impossable': '1,26€',
    '21%IVA': '0,26 €',
    'Preu Venta Públic': '1,52€',
  },
  {
    Referència: 'CU49',
    Descripció: 'Ou petit boix 5cm',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/729-ou-petit-boix.html',
    Imàtges:
      'https://can-cels.com/1046-technology_large_default/ou-petit-boix.jpg',
    'preu major': '0,28€',
    'Marge 50%': '0,14€',
    'Base Impossable': '0,42€',
    '21%IVA': '0,09 €',
    'Preu Venta Públic': '0,51€',
  },
  {
    Referència: 'CU12',
    Descripció: 'Ous de faig colors 5cm',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/732-ous-de-faig-colors.html',
    Imàtges:
      'https://can-cels.com/1052-technology_large_default/ous-de-faig-colors.jpg',
    'preu major': '0,50€',
    'Marge 50%': '0,25€',
    'Base Impossable': '0,75€',
    '21%IVA': '0,16 €',
    'Preu Venta Públic': '0,91€',
  },
  {
    Referència: 'CU48',
    Descripció: 'Pala crep de faig',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/623-pala-crep-de-faig.html',
    Imàtges:
      'https://can-cels.com/908-technology_large_default/pala-crep-de-faig.jpg',
    'preu major': '1,13€',
    'Marge 50%': '0,57€',
    'Base Impossable': '1,70€',
    '21%IVA': '0,36 €',
    'Preu Venta Públic': '2,05€',
  },
  {
    Referència: 'CU113',
    Descripció: 'Pala mànec tornejat de boix',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/636-692-pala-manec-tornejat-de-boix.html#/97-mida-35_cm',
    Imàtges:
      'https://can-cels.com/919-technology_large_default/pala-manec-tornejat-de-boix.jpg',
    'preu major': '2,89€',
    'Marge 50%': '1,45€',
    'Base Impossable': '4,34€',
    '21%IVA': '0,91 €',
    'Preu Venta Públic': '5,25€',
  },
  {
    Referència: 'CU117',
    Descripció: 'Pala mini de boix',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/634-690-pala-mini-de-boix.html#/266-mida-9_cm',
    Imàtges:
      'https://can-cels.com/922-technology_large_default/pala-mini-de-boix.jpg',
    'preu major': '0,66€',
    'Marge 50%': '0,33€',
    'Base Impossable': '0,99€',
    '21%IVA': '0,21 €',
    'Preu Venta Públic': '1,20€',
  },
  {
    Referència: 'JC55',
    Descripció: 'Pandereta',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/571-605-pandereta.html#/232-mida-18cm_o',
    Imàtges: 'https://can-cels.com/838-technology_large_default/pandereta.jpg',
    'preu major': '6,54€',
    'Marge 50%': '3,27€',
    'Base Impossable': '9,81€',
    '21%IVA': '2,06 €',
    'Preu Venta Públic': '11,87€',
  },
  {
    Referència: 'JC08',
    Descripció: 'Passa anelles',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/526-573-passa-anelles.html#/219-mida-20cm_o_x_25cm',
    Imàtges:
      'https://can-cels.com/798-technology_large_default/passa-anelles.jpg',
    'preu major': '5,87€',
    'Marge 50%': '2,94€',
    'Base Impossable': '8,81€',
    '21%IVA': '1,85 €',
    'Preu Venta Públic': '10,65€',
  },
  {
    Referència: 'DV93',
    Descripció: 'Peg doll',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/439-534-peg-doll.html#/204-mida-34_o_x_70mm',
    Imàtges: 'https://can-cels.com/983-technology_large_default/peg-doll.jpg',
    'preu major': '0,89€',
    'Marge 50%': '0,45€',
    'Base Impossable': '1,34€',
    '21%IVA': '0,28 €',
    'Preu Venta Públic': '1,62€',
  },
  {
    Referència: 'JC28',
    Descripció: 'Picaboles',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/517-563-picaboles.html#/207-mida-23_cm',
    Imàtges: 'https://can-cels.com/789-technology_large_default/picaboles.jpg',
    'preu major': '1,18€',
    'Marge 50%': '0,59€',
    'Base Impossable': '1,77€',
    '21%IVA': '0,37 €',
    'Preu Venta Públic': '2,14€',
  },
  {
    Referència: 'CU127',
    Descripció: 'Pinces de faig 13cm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/617-661-pinces-de-faig.html#/98-mida-13_cm',
    Imàtges:
      'https://can-cels.com/974-technology_large_default/pinces-de-faig.jpg',
    'preu major': '1,01€',
    'Marge 50%': '0,51€',
    'Base Impossable': '1,52€',
    '21%IVA': '0,32 €',
    'Preu Venta Públic': '1,83€',
  },
  {
    Referència: 'XE24',
    Descripció: 'Pinta telar',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/755-pinta-telar.html',
    Imàtges:
      'https://can-cels.com/1056-technology_large_default/pinta-telar.jpg',
    'preu major': '2,32€',
    'Marge 50%': '1,16€',
    'Base Impossable': '3,48€',
    '21%IVA': '0,73 €',
    'Preu Venta Públic': '4,21€',
  },
  {
    Referència: 'JC34',
    Descripció: 'Pito gruixut boix amb cordill',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/591-pito-gruixut-boix-amb-cordill.html',
    Imàtges:
      'https://can-cels.com/856-technology_large_default/pito-gruixut-boix-amb-cordill.jpg',
    'preu major': '0,50€',
    'Marge 50%': '0,25€',
    'Base Impossable': '0,75€',
    '21%IVA': '0,16 €',
    'Preu Venta Públic': '0,91€',
  },
  {
    Referència: 'JC34',
    Descripció: 'Pito llarg boix amb cordill',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/592-pito-llarg-boix-amb-cordill.html',
    Imàtges:
      'https://can-cels.com/994-technology_large_default/pito-llarg-boix-amb-cordill.jpg',
    'preu major': '0,50€',
    'Marge 50%': '0,25€',
    'Base Impossable': '0,75€',
    '21%IVA': '0,16 €',
    'Preu Venta Públic': '0,91€',
  },
  {
    Referència: 'JD47',
    Descripció: 'Plomier',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/511-plomier.html',
    Imàtges: 'https://can-cels.com/785-technology_large_default/plomier.jpg',
    'preu major': '5,95€',
    'Marge 50%': '2,98€',
    'Base Impossable': '8,93€',
    '21%IVA': '1,87 €',
    'Preu Venta Públic': '10,80€',
  },
  {
    Referència: 'JC61',
    Descripció: 'Portallapis',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/510-portallapis.html',
    Imàtges:
      'https://can-cels.com/784-technology_large_default/portallapis.jpg',
    'preu major': '2,14€',
    'Marge 50%': '1,07€',
    'Base Impossable': '3,21€',
    '21%IVA': '0,67 €',
    'Preu Venta Públic': '3,88€',
  },
  {
    Referència: 'XE43',
    Descripció: 'Posa agulles gran boix',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/723-posa-agulles-gran-boix.html',
    Imàtges:
      'https://can-cels.com/1068-technology_large_default/posa-agulles-gran-boix.jpg',
    'preu major': '2,47€',
    'Marge 50%': '1,24€',
    'Base Impossable': '3,71€',
    '21%IVA': '0,78 €',
    'Preu Venta Públic': '4,48€',
  },
  {
    Referència: 'XE58',
    Descripció: 'Posa agulles mini boix',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/725-posa-agulles-mini-boix.html',
    Imàtges:
      'https://can-cels.com/1069-technology_large_default/posa-agulles-mini-boix.jpg',
    'preu major': '2,01€',
    'Marge 50%': '1,01€',
    'Base Impossable': '3,02€',
    '21%IVA': '0,63 €',
    'Preu Venta Públic': '3,65€',
  },
  {
    Referència: 'XE44',
    Descripció: 'Posa agulles petit boix',
    Categoria: 'Labors',
    link: 'https://can-cels.com/ca/inici/724-posa-agulles-petit-boix.html',
    Imàtges:
      'https://can-cels.com/1070-technology_large_default/posa-agulles-petit-boix.jpg',
    'preu major': '2,12€',
    'Marge 50%': '1,06€',
    'Base Impossable': '3,18€',
    '21%IVA': '0,67 €',
    'Preu Venta Públic': '3,85€',
  },
  {
    Referència: 'JD36',
    Descripció: 'Quatre en ratlla',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/404-514-quatre-en-ratlla.html#/195-mida-18_x18cm',
    Imàtges:
      'https://can-cels.com/882-technology_large_default/quatre-en-ratlla.jpg',
    'preu major': '8,39€',
    'Marge 50%': '4,20€',
    'Base Impossable': '12,59€',
    '21%IVA': '2,64 €',
    'Preu Venta Públic': '15,23€',
  },
  {
    Referència: 'JC53',
    Descripció: 'Rellotge de sorra',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/506-560-rellotge-de-sorra-.html#/215-mida-1_minuto',
    Imàtges:
      'https://can-cels.com/780-technology_large_default/rellotge-de-sorra-.jpg',
    'preu major': '0,87€',
    'Marge 50%': '0,44€',
    'Base Impossable': '1,31€',
    '21%IVA': '0,27 €',
    'Preu Venta Públic': '1,58€',
  },
  {
    Referència: 'DV40',
    Descripció: 'Rodet de fil 24x31mm',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/418-458-rodet-de-fil.html#/162-mida-70x87mm',
    Imàtges:
      'https://can-cels.com/717-technology_large_default/rodet-de-fil.jpg',
    'preu major': '0,82€',
    'Marge 50%': '0,41€',
    'Base Impossable': '1,23€',
    '21%IVA': '0,26 €',
    'Preu Venta Públic': '1,49€',
  },
  {
    Referència: 'CU83',
    Descripció: 'RODILLO DE FAIG 20cm',
    Categoria: 'Cuina',
    link: 'https://can-cels.com/ca/inici/615-652-rodillo-de-faig.html#/105-mida-40_cm',
    Imàtges:
      'https://can-cels.com/971-technology_large_default/rodillo-de-faig.jpg',
    'preu major': '0,76€',
    'Marge 50%': '0,61€',
    'Base Impossable': '1,37€',
    '21%IVA': '0,29 €',
    'Preu Venta Públic': '1,66€',
  },
  {
    Referència: 'JC01',
    Descripció: 'Serpentina',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/539-serpentina.html',
    Imàtges: 'https://can-cels.com/811-technology_large_default/serpentina.jpg',
    'preu major': '2,69€',
    'Marge 50%': '1,35€',
    'Base Impossable': '4,04€',
    '21%IVA': '0,85 €',
    'Preu Venta Públic': '4,88€',
  },
  {
    Referència: 'JD52',
    Descripció: 'Set regletes matemàtiques (Cuisenaire)',
    Categoria: 'Material escolar',
    link: 'https://can-cels.com/ca/inici/505-559-set-regletes-matematiques-cuisenaire-.html#/214-mida-304_piezas',
    Imàtges:
      'https://can-cels.com/996-technology_large_default/set-regletes-matematiques-cuisenaire-.jpg',
    'preu major': '16,54€',
    'Marge 50%': '8,27€',
    'Base Impossable': '24,81€',
    '21%IVA': '5,21 €',
    'Preu Venta Públic': '30,02€',
  },
  {
    Referència: 'JC26',
    Descripció: 'Solitari',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/406-516-solitari.html#/194-mida-195_x_195',
    Imàtges: 'https://can-cels.com/709-technology_large_default/solitari.jpg',
    'preu major': '6,18€',
    'Marge 50%': '3,09€',
    'Base Impossable': '9,27€',
    '21%IVA': '1,95 €',
    'Preu Venta Públic': '11,22€',
  },
  {
    Referència: 'JD71',
    Descripció: 'Sonall 3 anelles',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/437-sonall-3-anelles.html',
    Imàtges:
      'https://can-cels.com/989-technology_large_default/sonall-3-anelles.jpg',
    'preu major': '2,18€',
    'Marge 50%': '1,09€',
    'Base Impossable': '3,27€',
    '21%IVA': '0,69 €',
    'Preu Venta Públic': '3,96€',
  },
  {
    Referència: 'JD90',
    Descripció: 'Sonall anella i cordons de colors',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/475-538-sonall-anella-i-cordons-de-colors.html#/206-mida-o_ext_80_con_4_bolas_o_35mm',
    Imàtges:
      'https://can-cels.com/999-technology_large_default/sonall-anella-i-cordons-de-colors.jpg',
    'preu major': '2,00€',
    'Marge 50%': '1,00€',
    'Base Impossable': '3,00€',
    '21%IVA': '0,63 €',
    'Preu Venta Públic': '3,63€',
  },
  {
    Referència: 'JD97',
    Descripció: 'Sonall anella i cordons de colors',
    Categoria: 'Primera infància',
    link: 'https://can-cels.com/ca/inici/474-537-sonall-anella-i-cordons-de-colors.html#/205-mida-o_ext_80_con_6_bolas_o_35mm',
    Imàtges:
      'https://can-cels.com/987-technology_large_default/sonall-anella-i-cordons-de-colors.jpg',
    'preu major': '2,62€',
    'Marge 50%': '1,31€',
    'Base Impossable': '3,93€',
    '21%IVA': '0,83 €',
    'Preu Venta Públic': '4,76€',
  },
  {
    Referència: 'JD78',
    Descripció: 'Tambor',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/668-tambor.html',
    Imàtges: 'https://can-cels.com/949-technology_large_default/tambor.jpg',
    'preu major': '16,75€',
    'Marge 50%': '8,38€',
    'Base Impossable': '25,13€',
    '21%IVA': '5,28 €',
    'Preu Venta Públic': '30,40€',
  },
  {
    Referència: 'JD72',
    Descripció: 'Tambor de cartró',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/566-599-tambor-de-cartro.html#/228-mida-20cm_o',
    Imàtges:
      'https://can-cels.com/833-technology_large_default/tambor-de-cartro.jpg',
    'preu major': '6,30€',
    'Marge 50%': '3,15€',
    'Base Impossable': '9,45€',
    '21%IVA': '1,98 €',
    'Preu Venta Públic': '11,43€',
  },
  {
    Referència: 'JD78',
    Descripció: 'Tambor de fusta i pell',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/567-600-tambor-de-fusta-i-pell.html#/228-mida-20cm_o',
    Imàtges:
      'https://can-cels.com/834-technology_large_default/tambor-de-fusta-i-pell.jpg',
    'preu major': '16,75€',
    'Marge 50%': '8,38€',
    'Base Impossable': '25,13€',
    '21%IVA': '5,28 €',
    'Preu Venta Públic': '30,40€',
  },
  {
    Referència: 'JC25',
    Descripció: 'Tangram colors',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/407-517-tangram-colors.html#/195-mida-18_x18cm',
    Imàtges:
      'https://can-cels.com/710-technology_large_default/tangram-colors.jpg',
    'preu major': '4,57€',
    'Marge 50%': '2,29€',
    'Base Impossable': '6,86€',
    '21%IVA': '1,44 €',
    'Preu Venta Públic': '8,29€',
  },
  {
    Referència: 'JC43',
    Descripció: 'Tangram negre',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/408-518-tangram-negre.html#/195-mida-18_x18cm',
    Imàtges:
      'https://can-cels.com/711-technology_large_default/tangram-negre.jpg',
    'preu major': '4,57€',
    'Marge 50%': '2,29€',
    'Base Impossable': '6,86€',
    '21%IVA': '1,44 €',
    'Preu Venta Públic': '8,29€',
  },
  {
    Referència: 'JD14',
    Descripció: 'Tauler escacs i dames',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/394-509-tauler-escacs-i-dames.html#/190-mida-355_x355_cm',
    Imàtges:
      'https://can-cels.com/699-technology_large_default/tauler-escacs-i-dames.jpg',
    'preu major': '8,39€',
    'Marge 50%': '4,20€',
    'Base Impossable': '12,59€',
    '21%IVA': '2,64 €',
    'Preu Venta Públic': '15,23€',
  },
  {
    Referència: 'JD10',
    Descripció: 'Tauler oca i parxís',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/400-513-tauler-oca-i-parxis.html#/190-mida-355_x355_cm',
    Imàtges:
      'https://can-cels.com/705-technology_large_default/tauler-oca-i-parxis.jpg',
    'preu major': '8,39€',
    'Marge 50%': '4,20€',
    'Base Impossable': '12,59€',
    '21%IVA': '2,64 €',
    'Preu Venta Públic': '15,23€',
  },
  {
    Referència: 'JC68',
    Descripció: 'Tiraxines',
    Categoria: 'Punteria',
    link: 'https://can-cels.com/ca/inici/551-tiraxines.html',
    Imàtges: 'https://can-cels.com/821-technology_large_default/tiraxines.jpg',
    'preu major': '2,42€',
    'Marge 50%': '2,42€',
    'Base Impossable': '4,84€',
    '21%IVA': '1,02 €',
    'Preu Venta Públic': '5,86€',
  },
  {
    Referència: 'PZ01',
    Descripció: 'Trencaclosques',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/413-527-trencaclosques.html#/199-mida-14_x_14',
    Imàtges:
      'https://can-cels.com/715-technology_large_default/trencaclosques.jpg',
    'preu major': '1,16€',
    'Marge 50%': '0,58€',
    'Base Impossable': '1,74€',
    '21%IVA': '0,37 €',
    'Preu Venta Públic': '2,11€',
  },
  {
    Referència: 'JC87',
    Descripció: 'Trencaclosques animals',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/411-525-trencaclosques-animals.html#/197-mida-17_23_cm',
    Imàtges:
      'https://can-cels.com/713-technology_large_default/trencaclosques-animals.jpg',
    'preu major': '2,48€',
    'Marge 50%': '1,49€',
    'Base Impossable': '3,97€',
    '21%IVA': '0,83 €',
    'Preu Venta Públic': '4,80€',
  },
  {
    Referència: 'JC27',
    Descripció: 'Tres en ratlla',
    Categoria: 'Jocs de taula',
    link: 'https://can-cels.com/ca/inici/405-515-tres-en-ratlla.html#/194-mida-195_x_195',
    Imàtges:
      'https://can-cels.com/708-technology_large_default/tres-en-ratlla.jpg',
    'preu major': '4,02€',
    'Marge 50%': '2,01€',
    'Base Impossable': '6,03€',
    '21%IVA': '1,27 €',
    'Preu Venta Públic': '7,30€',
  },
  {
    Referència: 'JD49',
    Descripció: 'Vaixell propulsat amb globus',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/544-vaixell-propulsat-amb-globus-.html',
    Imàtges:
      'https://can-cels.com/816-technology_large_default/vaixell-propulsat-amb-globus-.jpg',
    'preu major': '3,03€',
    'Marge 50%': '1,52€',
    'Base Impossable': '4,55€',
    '21%IVA': '0,95 €',
    'Preu Venta Públic': '5,50€',
  },
  {
    Referència: 'JD05',
    Descripció: 'Vehicles aeris assortits',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/496-vehicles-aeris-assortits.html',
    Imàtges:
      'https://can-cels.com/966-technology_large_default/vehicles-aeris-assortits.jpg',
    'preu major': '0,84€',
    'Marge 50%': '0,42€',
    'Base Impossable': '1,26€',
    '21%IVA': '0,26 €',
    'Preu Venta Públic': '1,52€',
  },
  {
    Referència: 'JD81',
    Descripció: 'Vehicles terrestres assortits',
    Categoria: 'Joc simbòlic',
    link: 'https://can-cels.com/ca/inici/497-551--vehicles-terrestres-assortits.html#/45-color-colors',
    Imàtges:
      'https://can-cels.com/772-technology_large_default/-vehicles-terrestres-assortits.jpg',
    'preu major': '0,76€',
    'Marge 50%': '0,38€',
    'Base Impossable': '1,14€',
    '21%IVA': '0,24 €',
    'Preu Venta Públic': '1,38€',
  },
  {
    Referència: 'JC23',
    Descripció: 'Xanques',
    Categoria: "Jocs d'habilitat",
    link: 'https://can-cels.com/ca/inici/525-xanques.html',
    Imàtges: 'https://can-cels.com/874-technology_large_default/xanques.jpg',
    'preu major': '6,14€',
    'Marge 50%': '3,07€',
    'Base Impossable': '9,21€',
    '21%IVA': '1,93 €',
    'Preu Venta Públic': '11,14€',
  },
  {
    Referència: 'JD50',
    Descripció: 'Xilòfon',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/588-xilofon.html',
    Imàtges: 'https://can-cels.com/852-technology_large_default/xilofon.jpg',
    'preu major': '3,68€',
    'Marge 50%': '1,84€',
    'Base Impossable': '5,52€',
    '21%IVA': '1,16 €',
    'Preu Venta Públic': '6,68€',
  },
  {
    Referència: 'JC15',
    Descripció: 'Xiulet de boix 5cm',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/589-626-xiulet-de-boix.html#/81-mida-5_cm',
    Imàtges:
      'https://can-cels.com/854-technology_large_default/xiulet-de-boix.jpg',
    'preu major': '0,44€',
    'Marge 50%': '0,22€',
    'Base Impossable': '0,66€',
    '21%IVA': '0,14 €',
    'Preu Venta Públic': '0,80€',
  },
  {
    Referència: 'JC62',
    Descripció: 'Zing- zing gran',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/569-603-zing-zing-gran.html#/99-mida-21_cm',
    Imàtges:
      'https://can-cels.com/836-technology_large_default/zing-zing-gran.jpg',
    'preu major': '2,00€',
    'Marge 50%': '1,00€',
    'Base Impossable': '3,00€',
    '21%IVA': '0,63 €',
    'Preu Venta Públic': '3,63€',
  },
  {
    Referència: 'JC71',
    Descripció: 'Zing- zing petit',
    Categoria: 'Música',
    link: 'https://can-cels.com/ca/inici/570-604-zing-zing-petit.html#/98-mida-13_cm',
    Imàtges:
      'https://can-cels.com/837-technology_large_default/zing-zing-petit.jpg',
    'preu major': '1,32€',
    'Marge 50%': '0,66€',
    'Base Impossable': '1,98€',
    '21%IVA': '0,42 €',
    'Preu Venta Públic': '2,40€',
  },
];
